import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createApp} from '../server.mjs';
import {emptyTrip,validateTrip} from '../lib/model.mjs';
import {esc,safeUrl} from '../public/shared.js';
const password='integration-test-password';
async function fixture(t,options={}){const dir=await mkdtemp(join(tmpdir(),'trip-test-'));let server=createApp({dataDir:dir,password,...options});await new Promise(r=>server.listen(0,'127.0.0.1',r));let base='http://127.0.0.1:'+server.address().port;let cookie='',csrf='';
 const call=(path,method='GET',value,headers={})=>fetch(base+path,{method,headers:{Cookie:cookie,'X-CSRF-Token':csrf,'Content-Type':'application/json',...headers},body:value===undefined?undefined:JSON.stringify(value)});
 async function login(){const response=await call('/api/login','POST',{password});assert.equal(response.status,200);cookie=response.headers.get('set-cookie').split(';')[0];csrf=(await response.json()).csrf;return response;}
 t.after(async()=>{await new Promise(r=>server.close(r));await rm(dir,{recursive:true,force:true});});
 return {dir,call,login,get base(){return base;},get cookie(){return cookie;},get csrf(){return csrf;},async restart(){await new Promise(r=>server.close(r));server=createApp({dataDir:dir,password,...options});await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;}};
}
test('private data, exports and attachments require login; secrets are not static files',async t=>{const f=await fixture(t);for(const p of ['/api/trip','/api/export','/api/attachments/00000000-0000-0000-0000-000000000000.pdf'])assert.equal((await f.call(p)).status,401);for(const p of ['/data/trip.json','/.env','/server.mjs','/data.js'])assert.equal((await f.call(p)).status,404);assert.equal((await f.call('/admin')).status,200);assert.equal((await f.call('/healthz')).status,200);});
test('password and CSRF protections, cookie flags, and logout',async t=>{const f=await fixture(t,{secureCookie:true});assert.equal((await f.call('/api/login','POST',{password:'wrong'})).status,401);const login=await f.login();assert.match(login.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);assert.match(login.headers.get('set-cookie'),/Secure/);assert.equal((await f.call('/api/trip')).status,200);assert.equal((await f.call('/api/trip','PUT',{revision:0,trip:emptyTrip()},{'X-CSRF-Token':''})).status,403);assert.equal((await f.call('/api/trip','PUT',{revision:0,trip:emptyTrip()},{Origin:'https://evil.example'})).status,403);assert.equal((await f.call('/api/logout','POST')).status,200);assert.equal((await f.call('/api/trip')).status,401);});
test('unconfigured deployment fails closed',async t=>{const f=await fixture(t,{password:''});assert.equal((await f.call('/api/login','POST',{password:''})).status,503);assert.equal((await f.call('/api/session').then(r=>r.json())).configured,false);});
test('failed login attempts are limited',async t=>{const f=await fixture(t);for(let i=0;i<10;i++)assert.equal((await f.call('/api/login','POST',{password:'wrong'})).status,401);assert.equal((await f.call('/api/login','POST',{password})).status,429);});
test('save, export, revision conflicts, previous backup, and server restart persistence',async t=>{const f=await fixture(t);await f.login();const trip=emptyTrip();trip.title='我的测试行程';let response=await f.call('/api/trip','PUT',{revision:0,trip});assert.equal(response.status,200);assert.equal((await response.json()).revision,1);assert.equal((await f.call('/api/trip','PUT',{revision:0,trip})).status,409);trip.title='修改后的行程';assert.equal((await f.call('/api/trip','PUT',{revision:1,trip})).status,200);assert.equal(JSON.parse(await readFile(join(f.dir,'trip.previous.json'),'utf8')).trip.title,'我的测试行程');assert.equal((await f.call('/api/export').then(r=>r.json())).title,'修改后的行程');await f.restart();assert.equal((await f.call('/api/trip')).status,401);await f.login();assert.equal((await f.call('/api/trip').then(r=>r.json())).trip.title,'修改后的行程');});
test('simultaneous edits cannot overwrite the same revision',async t=>{const f=await fixture(t);await f.login();const statuses=await Promise.all([f.call('/api/trip','PUT',{revision:0,trip:emptyTrip()}),f.call('/api/trip','PUT',{revision:0,trip:emptyTrip()})]);assert.deepEqual(statuses.map(r=>r.status).sort(),[200,409]);});
test('invalid imports and unsafe links are rejected without changing stored data',async t=>{const f=await fixture(t);await f.login();const trip=emptyTrip();trip.startDate='2026-02-30';assert.equal((await f.call('/api/validate','POST',trip)).status,400);trip.startDate='';trip.notes=[{id:'note1',title:'Unsafe',body:'',url:'javascript:alert(1)'}];assert.equal((await f.call('/api/trip','PUT',{revision:0,trip})).status,400);assert.equal((await f.call('/api/trip').then(r=>r.json())).revision,0);});
test('attachment content is checked, authenticated, and survives a restart',async t=>{const f=await fixture(t);await f.login();const headers={Cookie:f.cookie,'X-CSRF-Token':f.csrf,'X-File-Name':encodeURIComponent('凭证.pdf')};assert.equal((await fetch(f.base+'/api/attachments',{method:'POST',headers,body:'<script>bad</script>'})).status,400);const upload=await fetch(f.base+'/api/attachments',{method:'POST',headers,body:'%PDF-1.7\nfixture'});assert.equal(upload.status,201);const a=await upload.json();let r=await f.call('/api/attachments/'+a.id);assert.equal(r.status,200);assert.match(r.headers.get('content-disposition'),/^attachment/);await f.restart();await f.login();assert.equal(await(await f.call('/api/attachments/'+a.id)).text(),'%PDF-1.7\nfixture');});
test('HTML is escaped and links allow only HTTP(S)',()=>{assert.equal(esc('<img src=x onerror="bad">'),'&lt;img src=x onerror=&quot;bad&quot;&gt;');assert.equal(safeUrl('javascript:alert(1)'), '');assert.equal(safeUrl('https://example.com/'),'https://example.com/');});
test('duplicate IDs are rejected',()=>{const t=emptyTrip();t.notes=[{id:'a',title:'one',body:'',url:''},{id:'a',title:'two',body:'',url:''}];assert.throws(()=>validateTrip(t),/重复/);});
