import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createApp} from '../server.mjs';
import {emptyTrip,validateTrip} from '../lib/model.mjs';
import {esc,safeUrl} from '../public/shared.js';
import {mergeTrips} from '../public/merge.js';
import {planPartialUpdate} from '../public/partial-update.js';
import {preparationRows,pendingPreparationCount} from '../public/preparations.js';
import {shouldShowStopMap} from '../public/map-visibility.js';
import {normalizeAiResult,splitOrganizerSource} from '../lib/ai.mjs';
import {attachDocumentPhotos} from '../lib/photo-map.mjs';
import {organizeStopCopy} from '../lib/stop-copy.mjs';
import {feishuWikiUrl} from '../lib/feishu.mjs';
import {parseTaggedSections,applyTaggedSections,routeFromHeading} from '../lib/tagged-sections.mjs';
const password='integration-test-password';
async function fixture(t,options={}){const dir=await mkdtemp(join(tmpdir(),'trip-test-'));let server=createApp({dataDir:dir,password,...options});await new Promise(r=>server.listen(0,'127.0.0.1',r));let base='http://127.0.0.1:'+server.address().port;let cookie='',csrf='';
 const call=(path,method='GET',value,headers={})=>fetch(base+path,{method,headers:{Cookie:cookie,'X-CSRF-Token':csrf,'Content-Type':'application/json',...headers},body:value===undefined?undefined:JSON.stringify(value)});
 if(!options.unconfigured)assert.equal((await call('/api/setup','POST',{password,confirmPassword:password})).status,201);
 async function login(){const response=await call('/api/login','POST',{password});assert.equal(response.status,200);cookie=response.headers.get('set-cookie').split(';')[0];csrf=(await response.json()).csrf;return response;}
 t.after(async()=>{await new Promise(r=>server.close(r));await rm(dir,{recursive:true,force:true});});
 return {dir,call,login,get base(){return base;},get cookie(){return cookie;},get csrf(){return csrf;},async restart(){await new Promise(r=>server.close(r));server=createApp({dataDir:dir,password,...options});await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;}};
}
test('private data, exports and attachments require login; secrets are not static files',async t=>{const f=await fixture(t);for(const p of ['/api/trip','/api/export','/api/attachments/00000000-0000-0000-0000-000000000000.pdf'])assert.equal((await f.call(p)).status,401);for(const p of ['/data/trip.json','/.env','/server.mjs','/data.js'])assert.equal((await f.call(p)).status,404);assert.equal((await f.call('/admin')).status,200);assert.equal((await f.call('/healthz')).status,200);});
test('password and CSRF protections, cookie flags, and logout',async t=>{const f=await fixture(t,{secureCookie:true});assert.equal((await f.call('/api/login','POST',{password:'wrong'})).status,401);const login=await f.login();assert.match(login.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);assert.match(login.headers.get('set-cookie'),/Secure/);assert.equal((await f.call('/api/trip')).status,200);assert.equal((await f.call('/api/trip','PUT',{revision:0,trip:emptyTrip()},{'X-CSRF-Token':''})).status,403);assert.equal((await f.call('/api/trip','PUT',{revision:0,trip:emptyTrip()},{Origin:'https://evil.example'})).status,403);assert.equal((await f.call('/api/logout','POST')).status,200);assert.equal((await f.call('/api/trip')).status,401);});
test('first visit setup persists and cannot be claimed twice',async t=>{const f=await fixture(t,{unconfigured:true});assert.equal((await f.call('/api/login','POST',{password:''})).status,503);assert.equal((await f.call('/api/session').then(r=>r.json())).configured,false);assert.equal((await f.call('/api/setup','POST',{password:'short',confirmPassword:'short'})).status,400);const results=await Promise.all([f.call('/api/setup','POST',{password,confirmPassword:password}),f.call('/api/setup','POST',{password,confirmPassword:password})]);assert.deepEqual(results.map(r=>r.status).sort(),[201,409]);await f.restart();await f.login();const saved=await readFile(join(f.dir,'auth.json'),'utf8');assert.ok(!saved.includes(password));});
test('failed login attempts are limited',async t=>{const f=await fixture(t);for(let i=0;i<10;i++)assert.equal((await f.call('/api/login','POST',{password:'wrong'})).status,401);assert.equal((await f.call('/api/login','POST',{password})).status,429);});
test('save, export, revision conflicts, previous backup, and server restart persistence',async t=>{const f=await fixture(t);await f.login();const trip=emptyTrip();trip.title='我的测试行程';let response=await f.call('/api/trip','PUT',{revision:0,trip});assert.equal(response.status,200);assert.equal((await response.json()).revision,1);assert.equal((await f.call('/api/trip','PUT',{revision:0,trip})).status,409);trip.title='修改后的行程';assert.equal((await f.call('/api/trip','PUT',{revision:1,trip})).status,200);assert.equal(JSON.parse(await readFile(join(f.dir,'trips.previous.json'),'utf8')).trips[0].trip.title,'我的测试行程');assert.equal((await f.call('/api/export').then(r=>r.json())).title,'修改后的行程');await f.restart();assert.equal((await f.call('/api/trip')).status,401);await f.login();assert.equal((await f.call('/api/trip').then(r=>r.json())).trip.title,'修改后的行程');});
test('multiple trips keep separate revisions and allow switching and deletion',async t=>{const f=await fixture(t);await f.login();const first=await f.call('/api/trip').then(r=>r.json());first.trip.title='大阪';assert.equal((await f.call('/api/trips/'+first.id,'PUT',{revision:0,trip:first.trip})).status,200);const next=emptyTrip();next.title='巴黎';const created=await f.call('/api/trips','POST',{trip:next}).then(r=>r.json());assert.notEqual(created.id,first.id);assert.equal((await f.call('/api/trips').then(r=>r.json())).trips.length,2);assert.equal((await f.call('/api/trip').then(r=>r.json())).trip.title,'巴黎');assert.equal((await f.call('/api/trips/'+first.id).then(r=>r.json())).trip.title,'大阪');assert.equal((await f.call('/api/trips/active','PUT',{id:first.id})).status,200);assert.equal((await f.call('/api/trip').then(r=>r.json())).trip.title,'大阪');assert.equal((await f.call('/api/trips/'+created.id,'DELETE')).status,200);assert.equal((await f.call('/api/trips/'+first.id,'DELETE')).status,400);await f.restart();await f.login();assert.equal((await f.call('/api/trips').then(r=>r.json())).trips.length,1);});
test('legacy reservations and tickets are grouped by purpose without losing attachment references',()=>{const trip=emptyTrip();const file={id:'00000000-0000-0000-0000-000000000001.pdf',name:'确认单.pdf'};trip.bookings=[{id:'flight1',title:'去程航班',kind:'flight',date:'2026-10-15',endDate:'',time:'09:00',status:'confirmed',reference:'',location:'',cost:'',notes:'',url:'',attachment:null},{id:'hotel1',title:'Hotel Osaka',kind:'hotel',date:'2026-10-15',endDate:'2026-10-17',time:'',status:'confirmed',reference:'',location:'',cost:'',notes:'',url:'',attachment:file},{id:'dinner1',title:'晚餐预约',kind:'food',date:'2026-10-15',endDate:'',time:'19:00',status:'confirmed',reference:'',location:'',cost:'',notes:'',url:'',attachment:null}];trip.tickets=[{id:'salon1',title:'ECOO 理发预约',date:'2026-10-15',time:'15:00',status:'confirmed',reference:'',location:'',notes:'',url:'',attachment:null},{id:'bus1',title:'机场巴士',date:'2026-10-19',time:'',status:'pending',reference:'',location:'',notes:'',url:'',attachment:null}];const result=validateTrip(trip);assert.deepEqual(result.bookings.map(x=>x.id),['dinner1','salon1']);assert.deepEqual(result.tickets.map(x=>x.id),['flight1','hotel1','bus1']);assert.equal(result.tickets[1].attachment.name,'确认单.pdf');assert.equal(result.bookings[1].kind,'service');assert.equal(result.bookings[0].used,false);});
test('used reservations persist and attachment previews stay authenticated',async t=>{const f=await fixture(t);await f.login();const trip=emptyTrip();trip.bookings=[{id:'dinner1',title:'晚餐预约',kind:'food',date:'2026-10-15',endDate:'',time:'19:00',status:'confirmed',used:false,reference:'',location:'',cost:'',notes:'',url:'',attachment:null}];assert.equal((await f.call('/api/trip','PUT',{revision:0,trip})).status,200);const current=await f.call('/api/trip').then(r=>r.json());const route=`/api/trips/${current.id}/bookings/dinner1/used`;assert.equal((await f.call(route,'PATCH',{used:true},{'X-CSRF-Token':''})).status,403);assert.equal((await f.call(route,'PATCH',{used:true})).status,200);assert.equal((await f.call('/api/trip').then(r=>r.json())).trip.bookings[0].used,true);const png=Buffer.from([137,80,78,71,13,10,26,10]);const upload=await fetch(f.base+'/api/attachments',{method:'POST',headers:{Cookie:f.cookie,'X-CSRF-Token':f.csrf},body:png});const file=await upload.json();assert.equal((await f.call('/api/previews/'+file.id)).headers.get('content-disposition').startsWith('inline'),true);await f.call('/api/logout','POST');assert.equal((await f.call('/api/previews/'+file.id)).status,401);});
test('legacy single trip migrates without removing original data',async t=>{const f=await fixture(t);await f.login();const old=emptyTrip();old.title='旧行程';await writeFile(join(f.dir,'trip.json'),JSON.stringify({revision:3,updatedAt:null,trip:old}));const loaded=await f.call('/api/trip').then(r=>r.json());assert.equal(loaded.id,'legacy');assert.equal(loaded.trip.title,'旧行程');old.title='迁移后';assert.equal((await f.call('/api/trips/legacy','PUT',{revision:3,trip:old})).status,200);assert.equal(JSON.parse(await readFile(join(f.dir,'trip.json'),'utf8')).trip.title,'旧行程');assert.equal(JSON.parse(await readFile(join(f.dir,'trips.json'),'utf8')).trips[0].trip.title,'迁移后');});
test('MiMo model setting preserves the key and classification stays a preview',async t=>{let requested;const fetchImpl=async(url,options)=>{requested={url,options};return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify({trip:{title:'东京周末',days:[{date:'2026-10-15',city:'东京',stops:[{time:'09:00',title:'浅草散步'}]}],bookings:[{title:'酒店',kind:'hotel',status:'pending'}]},warnings:['确认酒店时间'],excluded:[]})}}]}),{status:200});};const f=await fixture(t,{fetchImpl});await f.login();assert.equal((await f.call('/api/ai/organize','POST',{source:'10月15日东京浅草散步，晚上住酒店，酒店还没有确认。'})).status,400);assert.equal((await f.call('/api/ai/settings','PUT',{apiKey:'test-key-for-classification'})).status,200);assert.deepEqual(await f.call('/api/ai/settings').then(r=>r.json()),{configured:true,model:'mimo-v2.6-pro'});assert.equal((await f.call('/api/ai/settings','PUT',{apiKey:'',model:'mimo-v2.6-flash'})).status,200);assert.equal((await f.call('/api/ai/settings','PUT',{model:'invalid model'})).status,400);const response=await f.call('/api/ai/organize','POST',{source:'10月15日东京浅草散步，晚上住酒店，酒店还没有确认。'});assert.equal(response.status,200);const preview=await response.json();assert.equal(preview.trip.days[0].stops[0].kind,'walk');assert.equal(preview.trip.tickets[0].status,'pending');assert.equal((await f.call('/api/trip').then(r=>r.json())).trip.title,'我的旅行');assert.equal(requested.url,'https://api.xiaomimimo.com/v1/chat/completions');assert.equal(requested.options.headers['api-key'],'test-key-for-classification');assert.equal(JSON.parse(requested.options.body).model,'mimo-v2.6-flash');assert.deepEqual(await f.call('/api/ai/settings').then(r=>r.json()),{configured:true,model:'mimo-v2.6-flash'});});
test('long Feishu style source is split by dates without dropping itinerary lines',()=>{const source=['大阪&神户','10月15日（周四）| 上海到大阪',...Array.from({length:35},(_,i)=>`第 ${i+1} 项安排：乘车、步行与预约信息。`),'10月16日（周五）| 大阪',...Array.from({length:35},(_,i)=>`第 ${i+36} 项安排：路线、价格与提示。`)].join('\n');const chunks=splitOrganizerSource(source,600);assert.ok(chunks.length>2);assert.ok(chunks.every(chunk=>chunk.text.length<=600));assert.ok(chunks.some(chunk=>chunk.contextDate.includes('10月15日')));assert.deepEqual(chunks.flatMap(chunk=>chunk.text.split('\n')).filter(Boolean),source.split('\n').filter(Boolean));});
test('AI automatically combines segmented days and retries truncated output with smaller sections',async t=>{let requests=0;const fetchImpl=async(_url,options)=>{requests++;if(requests===1)return new Response(JSON.stringify({choices:[{finish_reason:'length',message:{content:'{"trip":'}}]}),{status:200});const title=requests===2?'大阪散步':'神户散步';return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify({trip:{title:'大阪&神户',days:[{date:'2026-10-15',city:'大阪',stops:[{title,time:'09:00'}]}]},warnings:[],excluded:[]})}}]}),{status:200});};const f=await fixture(t,{fetchImpl});await f.login();await f.call('/api/ai/settings','PUT',{apiKey:'test-key-for-classification'});const source=['10月15日（周四）| 大阪',...Array.from({length:60},(_,i)=>`第${i+1}项：大阪购物与移动安排。`)].join('\n');const response=await f.call('/api/ai/organize','POST',{source});assert.equal(response.status,200);const preview=await response.json();assert.ok(requests>=3);assert.equal(preview.segments,2);assert.equal(preview.trip.days.length,1);assert.equal(preview.trip.days[0].stops.length,2);assert.equal((await f.call('/api/trip').then(r=>r.json())).trip.title,'我的旅行');});
test('AI missing titles and null fields become reviewable placeholders',()=>{const result=normalizeAiResult({trip:{title:'',days:[{date:'2026-10-15',city:null,stops:[{time:'9:00',title:'',kind:null,status:null}]}],bookings:[{title:null,kind:null,status:null}],notes:[{title:'',body:null}]},warnings:[],excluded:[]});assert.equal(result.trip.title,'未命名旅行');assert.equal(result.trip.days[0].city,'待定地点');assert.equal(result.trip.days[0].stops[0].title,'待核对事项');assert.equal(result.trip.days[0].stops[0].time,'09:00');assert.equal(result.trip.bookings[0].title,'待核对预订');assert.ok(result.warnings.some(w=>w.includes('旅行名称')));});
test('new AI imports do not create hidden notes and legacy notes remain exportable',()=>{const incoming=normalizeAiResult({trip:{title:'大阪',notes:[{title:'摄影建议',body:'花火使用手持相机。'}]}});assert.equal(incoming.trip.notes.length,0);assert.ok(incoming.warnings.some(w=>w.includes('摄影建议')));const legacy=emptyTrip();legacy.notes=[{id:'legacy-note',title:'旧攻略',body:'保留原文',url:''}];assert.equal(validateTrip(legacy).notes[0].body,'保留原文');});
test('front and admin pending counts use stop preparations, not legacy global checklist',()=>{const trip=emptyTrip();trip.checklist=Array.from({length:12},(_,i)=>({id:'old-'+i,title:'旧清单'+i,group:'旧版',done:false,notes:''}));trip.days=[{id:'day',date:'2026-10-17',city:'大阪',cityEn:'',theme:'',intro:'',stops:[{id:'stop',time:'14:30',endTime:'',title:'花火准备',titleEn:'',kind:'event',status:'planned',description:'',transport:'',tips:'',alternative:'',extensions:[],location:'',url:'',cost:'',source:'',photos:[],preparations:Array.from({length:8},(_,i)=>({id:'prep-'+i,title:'准备'+i,done:false}))}]}];assert.equal(preparationRows(trip).length,8);assert.equal(pendingPreparationCount(trip),8);trip.days[0].stops[0].preparations[0].done=true;assert.equal(pendingPreparationCount(trip),7);assert.equal(validateTrip(trip).checklist.length,12);});
test('new AI imports warn about unassigned global tasks instead of creating a second checklist',()=>{const result=normalizeAiResult({trip:{title:'大阪',checklist:[{title:'充电宝',group:'花火',done:false}]}});assert.equal(result.trip.checklist.length,0);assert.ok(result.warnings.some(w=>w.includes('充电宝')));});
test('a Feishu URL alone is rejected before any MiMo request',async t=>{let called=false;const f=await fixture(t,{fetchImpl:async()=>{called=true;throw Error('should not be called');}});await f.login();await f.call('/api/ai/settings','PUT',{apiKey:'test-key-for-classification'});const response=await f.call('/api/ai/organize','POST',{source:'https://my.feishu.cn/wiki/GpH0wi2Qyi4t1NkVN98cXYwunxd'});assert.equal(response.status,400);assert.match((await response.json()).error,/只有网页链接/);assert.equal(called,false);});
test('Feishu link import previews extracted text and limits the destination',async t=>{let received;const f=await fixture(t,{sourceReader:async url=>{received=url;return {title:'大阪和神户',source:'10月15日大阪行程正文，先从上海出发，再抵达关西机场。',characters:28,blocks:2};}});await f.login();assert.equal((await f.call('/api/ai/source','POST',{url:'http://127.0.0.1/wiki/GpH0wi2Qyi4t1NkVN98cXYwunxd'})).status,400);assert.equal((await f.call('/api/ai/source','POST',{url:'https://evil.example/wiki/GpH0wi2Qyi4t1NkVN98cXYwunxd'})).status,400);assert.equal(received,undefined);const response=await f.call('/api/ai/source','POST',{url:'https://my.feishu.cn/wiki/GpH0wi2Qyi4t1NkVN98cXYwunxd?query=ignored'});assert.equal(response.status,200);assert.equal(received,'https://my.feishu.cn/wiki/GpH0wi2Qyi4t1NkVN98cXYwunxd');assert.match((await response.json()).source,/大阪行程正文/);assert.equal((await f.call('/api/trip').then(r=>r.json())).trip.title,'我的旅行');});
test('Feishu wiki validation rejects credentials and other paths',()=>{assert.throws(()=>feishuWikiUrl('https://user:pass@my.feishu.cn/wiki/GpH0wi2Qyi4t1NkVN98cXYwunxd'));assert.throws(()=>feishuWikiUrl('https://my.feishu.cn/admin'));});
test('a direct AI trip object is accepted when MiMo omits the trip wrapper',()=>{const result=normalizeAiResult({title:'大阪和神户',days:[{date:'2026-10-15',city:'大阪',stops:[]}]});assert.equal(result.trip.title,'大阪和神户');assert.equal(result.trip.days.length,1);});
test('simultaneous edits cannot overwrite the same revision',async t=>{const f=await fixture(t);await f.login();const statuses=await Promise.all([f.call('/api/trip','PUT',{revision:0,trip:emptyTrip()}),f.call('/api/trip','PUT',{revision:0,trip:emptyTrip()})]);assert.deepEqual(statuses.map(r=>r.status).sort(),[200,409]);});
test('invalid imports and unsafe links are rejected without changing stored data',async t=>{const f=await fixture(t);await f.login();const trip=emptyTrip();trip.startDate='2026-02-30';assert.equal((await f.call('/api/validate','POST',trip)).status,400);trip.startDate='';trip.notes=[{id:'note1',title:'Unsafe',body:'',url:'javascript:alert(1)'}];assert.equal((await f.call('/api/trip','PUT',{revision:0,trip})).status,400);assert.equal((await f.call('/api/trip').then(r=>r.json())).revision,0);});
test('attachment content is checked, authenticated, and survives a restart',async t=>{const f=await fixture(t);await f.login();const headers={Cookie:f.cookie,'X-CSRF-Token':f.csrf,'X-File-Name':encodeURIComponent('凭证.pdf')};assert.equal((await fetch(f.base+'/api/attachments',{method:'POST',headers,body:'<script>bad</script>'})).status,400);const upload=await fetch(f.base+'/api/attachments',{method:'POST',headers,body:'%PDF-1.7\nfixture'});assert.equal(upload.status,201);const a=await upload.json();let r=await f.call('/api/attachments/'+a.id);assert.equal(r.status,200);assert.match(r.headers.get('content-disposition'),/^attachment/);await f.restart();await f.login();assert.equal(await(await f.call('/api/attachments/'+a.id)).text(),'%PDF-1.7\nfixture');});
test('stop preparations persist individually and photos render inline for signed-in visitors',async t=>{const f=await fixture(t);await f.login();const png=Buffer.from([137,80,78,71,13,10,26,10,0,0,0,0]);const upload=await fetch(f.base+'/api/attachments',{method:'POST',headers:{Cookie:f.cookie,'X-CSRF-Token':f.csrf,'X-File-Name':'reference.png'},body:png});assert.equal(upload.status,201);const photo=await upload.json();const trip=emptyTrip();trip.days=[{id:'day1',date:'2026-10-15',city:'大阪',cityEn:'',theme:'',intro:'',stops:[{id:'stop1',time:'19:00',endTime:'',title:'花火大会',titleEn:'Fireworks',kind:'event',status:'planned',description:'提前入场',transport:'步行',tips:'带水',alternative:'雨天取消',location:'大阪',url:'',cost:'',source:'',preparations:[{id:'prep1',title:'带雨衣',done:false},{id:'prep2',title:'带水',done:false}],photos:[{...photo,caption:'观赏位置'}]}]}];assert.equal((await f.call('/api/trip','PUT',{revision:0,trip})).status,200);const current=await f.call('/api/trip').then(r=>r.json());const path=`/api/trips/${current.id}/stops/stop1/preparations/prep1`;assert.equal((await f.call(path,'PATCH',{done:true},{'X-CSRF-Token':''})).status,403);assert.equal((await f.call(path,'PATCH',{done:true})).status,200);assert.equal((await f.call('/api/trip').then(r=>r.json())).trip.days[0].stops[0].preparations[0].done,true);const image=await f.call('/api/photos/'+photo.id);assert.equal(image.status,200);assert.match(image.headers.get('content-disposition'),/^inline/);assert.equal(image.headers.get('content-type'),'image/png');await f.restart();await f.login();assert.equal((await f.call('/api/trip').then(r=>r.json())).trip.days[0].stops[0].preparations[0].done,true);});
test('AI keeps only inline document photo markers',()=>{const image='00000000-0000-0000-0000-000000000001.png';const result=normalizeAiResult({trip:{title:'大阪',days:[{city:'大阪',stops:[{title:'赏花火',photos:[{id:image,name:'文档图'},{id:'00000000-0000-0000-0000-000000000002.png',name:'外部图'}],preparations:[{title:'带水'}],tips:'注意散场'}]}]}},new Set([image]));const stop=result.trip.days[0].stops[0];assert.equal(stop.photos.length,1);assert.equal(stop.photos[0].id,image);assert.equal(stop.preparations.length,1);assert.equal(stop.preparations[0].done,false);assert.equal(stop.tips,'注意散场');});
test('document photos attach to their nearby destination, including photos before a stop heading',()=>{const church='00000000-0000-0000-0000-000000000001.png',dinner='00000000-0000-0000-0000-000000000002.png';const source=['10月18日（周日）| 神户','09:10 - 09:30 | 神户酒店寄存行李','09:30 - 10:05 | 神户中央教堂（外观摄影）','提醒：在教堂外拍建筑与光影。',`【文档内拍照参考图片：${church}】`,'10:05 - 10:35 | 教堂 → 旧居留地','11:40 - 12:00 | 前往 Steak Ishida','神户牛 Ishida 点单攻略',`【文档内图片参考：${dinner}】`,'12:00 - 13:30 | Steak Ishida 神户牛午餐'].join('\n');const trip=emptyTrip();trip.days=[{id:'day1',date:'2026-10-18',city:'神户',cityEn:'',theme:'',intro:'',stops:[{id:'hotel',time:'09:10',title:'神户酒店寄存行李',kind:'hotel',description:'',photos:[]},{id:'church',time:'09:30',title:'神户中央教堂',kind:'walk',description:'',photos:[]},{id:'move',time:'11:40',title:'前往 Steak Ishida',kind:'transport',description:'',photos:[]},{id:'ishida',time:'12:00',title:'Steak Ishida 神户牛午餐',kind:'food',description:'',photos:[]}]}];const result=attachDocumentPhotos(trip,source);assert.equal(result.photoCount,2);assert.deepEqual(result.unassigned,[]);assert.deepEqual(trip.days[0].stops.map(stop=>stop.photos.map(photo=>photo.id)),[[],[church],[],[dinner]]);});
test('AI does not display generic provenance copy as a source',()=>{const result=normalizeAiResult({trip:{title:'大阪',days:[{city:'大阪',stops:[{title:'大阪城',source:'原文行程 · 未重新核实时刻与营业安排'}]}]}},new Set());assert.equal(result.trip.days[0].stops[0].source,'');});
test('route copy is separated from on-site activity without swallowing a timetable',()=>{const stop={description:'路线：从酒店步行至 JR 大阪站。\n到站后购买车票。\n从酒店步行至 JR 大阪站。',transport:'',tips:''};organizeStopCopy(stop);assert.equal(stop.transport,'从酒店步行至 JR 大阪站。');assert.equal(stop.description,'到站后购买车票。');const schedule={description:'Haruka 候选班次：12:14→13:01、12:44→13:31。',transport:'优先乘 Haruka。'};organizeStopCopy(schedule);assert.match(schedule.description,/候选班次/);assert.equal(schedule.transport,'优先乘 Haruka。');});
test('HTML is escaped and links allow only HTTP(S)',()=>{assert.equal(esc('<img src=x onerror="bad">'),'&lt;img src=x onerror=&quot;bad&quot;&gt;');assert.equal(safeUrl('javascript:alert(1)'), '');assert.equal(safeUrl('https://example.com/'),'https://example.com/');});
test('map links skip origins, repeated airport and hotel stops, but keep new destinations',()=>{const stops=[
 {title:'钟翠苑住宅（起床）',location:'钟翠苑住宅'},
 {title:'上海浦东机场 T2',location:'上海浦东国际机场 T2'},
 {title:'机场流程',location:'上海浦东国际机场 T2 航站楼'},
 {title:'关西机场 T2',location:'关西国际机场 T2'},
 {title:'JR关西机场站',location:'大阪关西国际机场 T1'},
 {title:'酒店周边散步',location:'Hotel Vischio Osaka'},
 {title:'Hotel Vischio Osaka 酒店',location:'Hotel Vischio Osaka 酒店'},
 {title:'酒店（取行李）',location:'Hotel Vischio Osaka'},
 {title:'心斋桥',location:'心斋桥'},
 {title:'Hotel Vischio Osaka 酒店',location:'Hotel Vischio Osaka 酒店'},
 ];assert.deepEqual(stops.map((_,i)=>shouldShowStopMap(stops,i)),[false,true,false,true,false,false,true,false,true,true]);});
test('partial import fills a missing day without changing adjacent dates',()=>{const current=emptyTrip();current.startDate='2026-10-15';current.endDate='2026-10-17';current.days=[{id:'d15',date:'2026-10-15',city:'大阪',stops:[{id:'a',time:'09:00',title:'机场'}]},{id:'d17',date:'2026-10-17',city:'大阪',stops:[{id:'c',time:'09:00',title:'花火'}]}];const incoming=emptyTrip();incoming.days=[{id:'d16',date:'2026-10-16',city:'大阪',stops:[{id:'b',time:'10:00',title:'梅田'}]}];const {trip,changes}=planPartialUpdate(current,incoming,{date:'2026-10-16',mode:'add'});assert.deepEqual(trip.days.map(day=>day.date),['2026-10-15','2026-10-16','2026-10-17']);assert.equal(trip.days[1].stops[0].title,'梅田');assert.deepEqual(changes,{added:1,updated:0,removed:0,bookings:{added:0,updated:0},tickets:{added:0,updated:0}});assert.equal(current.days.length,2);});
test('partial update preserves outside hours, checked preparations, photos and ticket attachment',()=>{const current=emptyTrip();current.days=[{id:'day',date:'2026-10-16',city:'大阪',stops:[{id:'early',time:'08:00',title:'早餐'},{id:'shop',time:'14:00',title:'旧商店',description:'旧',preparations:[{id:'prep',title:'相机',done:true}],photos:[{id:'00000000-0000-0000-0000-000000000001.jpg',name:'旧照片',caption:''}],extensions:[]},{id:'late',time:'20:00',title:'晚餐'}]}];current.tickets=[{id:'ticket',date:'2026-10-16',time:'14:00',kind:'admission',title:'门票',reference:'OLD',attachment:{id:'00000000-0000-0000-0000-000000000002.pdf',name:'原件'}}];const incoming=emptyTrip();incoming.days=[{id:'newday',date:'2026-10-16',city:'大阪',stops:[{id:'replacement',time:'14:00',title:'新商店',description:'新',preparations:[{id:'newprep',title:'相机',done:false}],photos:[],extensions:[]}]}];incoming.tickets=[{id:'newticket',date:'2026-10-16',time:'14:00',kind:'admission',title:'门票',reference:'NEW',attachment:null}];const {trip,changes}=planPartialUpdate(current,incoming,{date:'2026-10-16',start:'13:00',end:'18:00',mode:'update'});assert.deepEqual(trip.days[0].stops.map(stop=>stop.id),['early','shop','late']);assert.equal(trip.days[0].stops[1].title,'新商店');assert.equal(trip.days[0].stops[1].preparations[0].done,true);assert.equal(trip.days[0].stops[1].photos.length,1);assert.equal(trip.tickets[0].reference,'NEW');assert.equal(trip.tickets[0].attachment.name,'原件');assert.equal(changes.updated,1);assert.equal(changes.tickets.updated,1);});
test('partial replacement removes only selected hours and rejects out-of-scope content',()=>{const current=emptyTrip();current.days=[{id:'day',date:'2026-10-16',city:'大阪',stops:[{id:'a',time:'09:00',title:'A'},{id:'b',time:'13:00',title:'B'},{id:'c',time:'16:00',title:'C'},{id:'d',time:'19:00',title:'D'}]}];const incoming=emptyTrip();incoming.days=[{id:'newday',date:'2026-10-16',city:'大阪',stops:[{id:'e',time:'14:00',title:'E'}]}];const {trip,changes}=planPartialUpdate(current,incoming,{date:'2026-10-16',start:'12:00',end:'17:00',mode:'replace'});assert.deepEqual(trip.days[0].stops.map(stop=>stop.title),['A','E','D']);assert.equal(changes.removed,2);incoming.days[0].date='2026-10-17';assert.throws(()=>planPartialUpdate(current,incoming,{date:'2026-10-16',mode:'add'}),/目标日期以外/);});
test('duplicate IDs are rejected',()=>{const t=emptyTrip();t.notes=[{id:'a',title:'one',body:'',url:''},{id:'a',title:'two',body:'',url:''}];assert.throws(()=>validateTrip(t),/重复/);});
test('AI merge keeps existing bookings, adds document photos, and avoids duplicate stops',()=>{const image='00000000-0000-0000-0000-000000000001.png';const current=emptyTrip();current.days=[{id:'day1',date:'2026-10-15',city:'大阪',cityEn:'',theme:'',intro:'',stops:[{id:'stop1',time:'09:00',title:'大阪城',photos:[]}]}];current.bookings=[{id:'booking1',title:'酒店',date:'2026-10-15',kind:'hotel',attachment:{id:'00000000-0000-0000-0000-000000000000.pdf',name:'凭证'}}];const incoming=emptyTrip();incoming.title='大阪旅行';incoming.days=[{id:'day2',date:'2026-10-15',city:'大阪',cityEn:'',theme:'',intro:'',stops:[{id:'stop2',time:'09:00',title:'大阪城',photos:[{id:image,name:'文档图片',caption:'大阪城'}]},{id:'stop3',time:'11:00',title:'道顿堀'}]}];incoming.bookings=[{id:'booking2',title:'酒店',date:'2026-10-15',kind:'hotel'}];const result=mergeTrips(current,incoming);assert.equal(result.title,'大阪旅行');assert.equal(result.days.length,1);assert.equal(result.days[0].stops.length,2);assert.deepEqual(result.days[0].stops[0].photos.map(photo=>photo.id),[image]);assert.equal(result.bookings.length,1);assert.equal(result.bookings[0].attachment.name,'凭证');});
test('tagged Feishu sections preserve separate named expansions and reminders',()=>{const source=['10月15日（周四）｜大阪','12:20 - 13:35 | JR大阪站（乘车）','摘要：优先选择更早抵达的车次。','提醒：','票务：HARUKA 需另购特急券。','【扩展｜参考车次】','12:14 → 13:01','12:44 → 13:31','【扩展｜交通方案】','PLAN A｜HARUKA','PLAN B｜JR关空快速','13:35 - 13:50 | 酒店','摘要：寄存行李。'].join('\n');const parsed=parseTaggedSections(source,'2026');assert.equal(parsed.length,2);assert.deepEqual(parsed[0].extensions.map(e=>e.title),['参考车次','交通方案']);const trip=emptyTrip();trip.startDate='2026-10-15';trip.days=[{id:'day1',date:'2026-10-15',city:'大阪',stops:[{id:'stop1',time:'12:20',title:'JR大阪站',kind:'transport',status:'planned',description:'',transport:'',tips:'',alternative:'',photos:[],preparations:[]},{id:'stop2',time:'13:35',title:'酒店',kind:'hotel',status:'planned',description:'',transport:'',tips:'',alternative:'',photos:[],preparations:[]}]}];const result=applyTaggedSections(trip,source);assert.deepEqual(result,{records:2,matched:2,extensions:2,recovered:0});const saved=validateTrip(trip).days[0].stops[0];assert.equal(saved.description,'优先选择更早抵达的车次。');assert.equal(saved.tips,'票务：HARUKA 需另购特急券。');assert.match(saved.extensions[0].body,/12:44/);assert.match(saved.extensions[1].body,/PLAN B/);assert.equal(saved.extensions[1].title,'交通方案');});
test('tagged expansion restores a stop omitted by MiMo',()=>{const source=['10月19日｜神户','15:20 - 16:36 | 关西机场 T2（机场巴士）','摘要：搭乘利木津巴士。','【扩展｜备用班次】','如未赶上首班车，改乘下一班。'].join('\n');const trip=emptyTrip();trip.startDate='2026-10-19';trip.cityTo='神户';trip.days=[];const result=applyTaggedSections(trip,source);assert.equal(result.recovered,1);assert.equal(trip.days[0].stops[0].time,'15:20');assert.equal(validateTrip(trip).days[0].stops[0].extensions[0].title,'备用班次');});
test('heading route and every reminder line survive a structured import',()=>{const source=['10月17日（周六）｜大阪','10:00 - 11:30 | LUCUA SOUTH 商场 / 梅田区域（步行前往，预计5–10分钟）','摘要：查漏补缺。','**提醒：**','- **查漏补缺：** 如果16日有未买到的 HOKA / KEEN，可根据距离快速插入。','- Nintendo OSAKA、Pokémon Center Osaka均集中在LUCUA SOUTH 13F。','11:30 - 11:45 | 中崎町（午餐）','摘要：吃午餐。'].join('\n');const parsed=parseTaggedSections(source,'2026');assert.equal(parsed[0].route,'步行前往，预计5–10分钟');assert.equal(parsed[0].reminders.length,2);assert.equal(routeFromHeading(parsed[1].heading),'');const trip=emptyTrip();trip.startDate='2026-10-17';applyTaggedSections(trip,source);const stop=validateTrip(trip).days[0].stops[0];assert.equal(stop.transport,'步行前往，预计5–10分钟');assert.match(stop.tips,/HOKA/);assert.match(stop.tips,/Nintendo OSAKA/);assert.equal(stop.title,'LUCUA SOUTH 商场 / 梅田区域');});
test('structured source keeps checklist items and reference links with their stop',()=>{const source=['10月17日｜大阪','14:30 - 15:20 | 酒店（换装）','摘要：整理花火物资。','代办：','野餐垫','充电宝','参考：相关说明','https://example.com/fireworks'].join('\n');const trip=emptyTrip();trip.startDate='2026-10-17';applyTaggedSections(trip,source);const stop=validateTrip(trip).days[0].stops[0];assert.deepEqual(stop.preparations.map(item=>item.title),['野餐垫','充电宝']);assert.equal(stop.url,'https://example.com/fireworks');});
test('regional shopping source keeps navigation point, ordered shops and reminders separate from summary',()=>{const source=['10月16日（周五）｜梅田 → 难波','09:50 - 12:40 | 梅田采购板块','- 导航点：Alpen OSAKA','- 路线：从酒店步行约5–10分钟。','- 逛店顺序','&#x20; \\- Alpen OSAKA：HOKA / KEEN','&#x20; \\- 【补货】LUCUA 1100 6F｜KEEN GARAGE OSAKA：Alpen未买到时进入。','- 重点：12:40前结束。','- 提醒：17日仍可补漏。'].join('\n');const trip=emptyTrip();trip.startDate='2026-10-16';const result=applyTaggedSections(trip,source);assert.equal(result.records,1);const stop=validateTrip(trip).days[0].stops[0];assert.equal(stop.layout,'area');assert.equal(stop.location,'Alpen OSAKA');assert.equal(stop.description,'');assert.equal(stop.transport,'从酒店步行约5–10分钟。');assert.deepEqual(stop.shops.map(shop=>shop.name),['Alpen OSAKA','LUCUA 1100 6F｜KEEN GARAGE OSAKA']);assert.equal(stop.shops[1].tag,'补货');assert.equal(stop.shops[1].location,'KEEN GARAGE OSAKA LUCUA Osaka');assert.match(stop.tips,/12:40前结束/);assert.match(stop.tips,/17日仍可补漏/);});
test('MiMo preview restores tagged sections even when the model omits them',async t=>{const fetchImpl=async()=>new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify({trip:{title:'大阪',startDate:'2026-10-15',days:[{date:'2026-10-15',city:'大阪',stops:[{time:'12:20',title:'JR大阪站',description:'模型概括',tips:''}]}]}})}}]}),{status:200});const f=await fixture(t,{fetchImpl});await f.login();await f.call('/api/ai/settings','PUT',{apiKey:'test-key-for-classification'});const source=['10月15日（周四）｜大阪','12:20 - 13:35 | JR大阪站（乘车）','摘要：原文摘要。','提醒：原文提醒。','【扩展｜交通方案】','优先乘坐 HARUKA。'].join('\n');const response=await f.call('/api/ai/organize','POST',{source});assert.equal(response.status,200);const stop=(await response.json()).trip.days[0].stops[0];assert.equal(stop.description,'原文摘要。');assert.equal(stop.tips,'原文提醒。');assert.deepEqual(stop.extensions.map(e=>e.title),['交通方案']);assert.equal(stop.extensions[0].body,'优先乘坐 HARUKA。');});
