import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createApp} from '../server.mjs';
import {emptyTrip} from '../lib/model.mjs';

test('trip sharing limits reading, editing, chat, and attachments to the granted trip',async t=>{
 const directory=await mkdtemp(join(tmpdir(),'trip-sharing-'));
 let server=createApp({dataDir:directory}),base,cookie='',csrf='';
 async function listen(){await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base='http://127.0.0.1:'+server.address().port;}
 await listen();
 t.after(async()=>{await new Promise(resolve=>server.close(resolve));await rm(directory,{recursive:true,force:true});});
 const call=(path,method='GET',data)=>fetch(base+path,{method,headers:{Cookie:cookie,'X-CSRF-Token':csrf,'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});
 const login=async username=>{const response=await call('/api/login','POST',{username,password:'sharing-test-password'});assert.equal(response.status,200);cookie=response.headers.get('set-cookie').split(';')[0];csrf=(await response.json()).csrf;};
 const upload=async path=>fetch(base+path,{method:'POST',headers:{Cookie:cookie,'X-CSRF-Token':csrf,'X-File-Name':'photo.jpg'},body:Buffer.from([255,216,255,217])});
 assert.equal((await call('/api/setup','POST',{password:'sharing-test-password',confirmPassword:'sharing-test-password'})).status,201);
 assert.equal((await call('/api/owner/claim','POST',{username:'owner',password:'sharing-test-password',confirmPassword:'sharing-test-password'})).status,201);
 await login('owner');
 const first=await call('/api/trip').then(r=>r.json()),tripA=first.id;
 const photoA=await upload('/api/attachments').then(r=>r.json());
 const planA=emptyTrip();planA.title='大阪行程';planA.days=[{id:'day-a',date:'2026-10-15',city:'大阪',stops:[{id:'stop-a',time:'09:00',title:'大阪城',kind:'museum',status:'planned',preparations:[{id:'prep-a',title:'带水',done:false}],photos:[{...photoA,caption:''}]}]}];
 assert.equal((await call('/api/trips/'+tripA,'PUT',{revision:first.revision,trip:planA})).status,200);
 const planB=emptyTrip();planB.title='私人东京行程';planB.days=[{id:'day-b',date:'2026-11-01',city:'东京',stops:[{id:'stop-b',time:'10:00',title:'秘密地点',kind:'walk',status:'planned'}]}];
 const created=await call('/api/trips','POST',{trip:planB}).then(r=>r.json()),tripB=created.id;
 const photoB=await upload('/api/attachments').then(r=>r.json());
 planB.days[0].stops[0].photos=[{...photoB,caption:''}];
 assert.equal((await call('/api/trips/'+tripB,'PUT',{revision:created.revision,trip:planB})).status,200);
 const viewer=(await call('/api/register','POST',{username:'viewer',password:'sharing-test-password',confirmPassword:'sharing-test-password'}).then(r=>r.json())).user;
 const editor=(await call('/api/register','POST',{username:'editor',password:'sharing-test-password',confirmPassword:'sharing-test-password'}).then(r=>r.json())).user;
 assert.equal((await call('/api/trips/'+tripA+'/shares/'+viewer.id,'PUT',{permission:'view'})).status,400);
 for(const user of [viewer,editor])assert.equal((await call('/api/users/'+user.id,'PATCH',{action:'approve'})).status,200);
 await login('viewer');
 assert.equal((await call('/api/trips').then(r=>r.json())).trips.length,0);
 assert.equal((await call('/api/trips/'+tripA)).status,404);
 assert.equal((await call('/api/photos/'+photoA.id)).status,404);
 await login('owner');
 assert.equal((await call('/api/trips/'+tripA+'/shares/'+viewer.id,'PUT',{permission:'view'})).status,200);
 assert.equal((await call('/api/trips/'+tripB+'/shares/'+editor.id,'PUT',{permission:'edit'})).status,200);
 const grants=await call('/api/trips/'+tripA+'/shares').then(r=>r.json());
 assert.equal(grants.shares[0].username,'viewer');
 await login('viewer');
 let listing=await call('/api/trips').then(r=>r.json());
 assert.deepEqual(listing.trips.map(t=>t.id),[tripA]);
 assert.equal(listing.trips[0].permission,'view');
 assert.equal(listing.activeTripId,tripA);
 assert.equal((await call('/api/trips/'+tripA).then(r=>r.json())).permission,'view');
 assert.equal((await call('/api/trips/'+tripB)).status,404);
 assert.equal((await call('/api/photos/'+photoA.id)).status,200);
 assert.equal((await call('/api/photos/'+photoB.id)).status,404);
 assert.equal((await call('/api/trips/'+tripA,'PUT',{revision:1,trip:planA})).status,403);
 assert.equal((await call('/api/trips/'+tripA+'/stops/stop-a/progress','PATCH',{progress:'completed'})).status,403);
 assert.equal((await call('/api/trips/'+tripA+'/stops/stop-a/preparations/prep-a','PATCH',{done:true})).status,403);
 assert.equal((await call('/api/trips/'+tripA+'/chat','POST',{text:'请修改',allowEdits:true})).status,403);
 assert.equal((await call('/api/trip')).status,403);
 assert.equal((await call('/api/users')).status,403);
 assert.equal((await call('/api/backup')).status,403);
 await login('editor');
 listing=await call('/api/trips').then(r=>r.json());
 assert.deepEqual(listing.trips.map(t=>t.id),[tripB]);
 assert.equal((await call('/api/trips/'+tripA)).status,404);
 const currentB=await call('/api/trips/'+tripB).then(r=>r.json());
 const forged=structuredClone(currentB.trip);forged.days[0].stops[0].photos=[{...photoA,caption:''}];
 assert.equal((await call('/api/trips/'+tripB,'PUT',{revision:currentB.revision,trip:forged})).status,403);
 currentB.trip.days[0].stops[0].title='已调整地点';
 assert.equal((await call('/api/trips/'+tripB,'PUT',{revision:currentB.revision,trip:currentB.trip})).status,200);
 const ownPhoto=await upload('/api/attachments?trip='+tripB);
 assert.equal(ownPhoto.status,201);
 const ownAsset=await ownPhoto.json();
 assert.equal((await call('/api/photos/'+ownAsset.id)).status,200);
 const updatedB=await call('/api/trips/'+tripB).then(r=>r.json());updatedB.trip.days[0].stops[0].photos=[{...ownAsset,caption:''}];
 assert.equal((await call('/api/trips/'+tripB,'PUT',{revision:updatedB.revision,trip:updatedB.trip})).status,200);
 assert.equal((await upload('/api/attachments?trip='+tripA)).status,404);
 assert.equal((await call('/api/trips/'+tripB+'/stops/stop-b/progress','PATCH',{progress:'completed'})).status,200);
 assert.equal((await call('/api/update')).status,403);
 await login('owner');
 assert.equal((await call('/api/trips/'+tripA+'/shares/'+viewer.id,'PUT',{permission:'edit'})).status,200);
 await login('viewer');
 assert.equal((await call('/api/trips/'+tripA+'/stops/stop-a/progress','PATCH',{progress:'completed'})).status,200);
 await new Promise(resolve=>server.close(resolve));server=createApp({dataDir:directory});await listen();
 await login('viewer');
 assert.equal((await call('/api/trips').then(r=>r.json())).trips[0].permission,'edit');
 await login('owner');
 assert.equal((await call('/api/trips/'+tripA+'/shares/'+viewer.id,'DELETE')).status,200);
 await login('viewer');
 assert.equal((await call('/api/trips').then(r=>r.json())).trips.length,0);
 assert.equal((await call('/api/trips/'+tripA)).status,404);
 assert.equal((await call('/api/photos/'+photoA.id)).status,404);
});

test('each approved account owns separate trips and can share one trip without exposing the others',async t=>{
 const directory=await mkdtemp(join(tmpdir(),'trip-owners-'));
 const server=createApp({dataDir:directory});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 t.after(async()=>{await new Promise(resolve=>server.close(resolve));await rm(directory,{recursive:true,force:true});});
 const base='http://127.0.0.1:'+server.address().port;let cookie='',csrf='';
 const call=(path,method='GET',data)=>fetch(base+path,{method,headers:{Cookie:cookie,'X-CSRF-Token':csrf,'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});
 async function login(username){const response=await call('/api/login','POST',{username,password:'sharing-test-password'});assert.equal(response.status,200);cookie=response.headers.get('set-cookie').split(';')[0];csrf=(await response.json()).csrf;}
 assert.equal((await call('/api/setup','POST',{password:'sharing-test-password',confirmPassword:'sharing-test-password'})).status,201);
 const owner=(await call('/api/owner/claim','POST',{username:'owner',password:'sharing-test-password',confirmPassword:'sharing-test-password'}).then(r=>r.json())).user;
 await login('owner');const legacyId=(await call('/api/trip').then(r=>r.json())).id;
 const alice=(await call('/api/register','POST',{username:'alice',password:'sharing-test-password',confirmPassword:'sharing-test-password'}).then(r=>r.json())).user;
 const bob=(await call('/api/register','POST',{username:'bob',password:'sharing-test-password',confirmPassword:'sharing-test-password'}).then(r=>r.json())).user;
 for(const user of [alice,bob])assert.equal((await call('/api/users/'+user.id,'PATCH',{action:'approve'})).status,200);
 await login('alice');const first=emptyTrip();first.title='Alice 的大阪';const second=emptyTrip();second.title='Alice 的京都';
 const osaka=await call('/api/trips','POST',{trip:first}).then(r=>r.json()),kyoto=await call('/api/trips','POST',{trip:second}).then(r=>r.json());
 assert.equal(osaka.ownerId,alice.id);assert.deepEqual((await call('/api/trips').then(r=>r.json())).trips.map(t=>t.id),[osaka.id,kyoto.id]);
 assert.equal((await call('/api/trips/'+legacyId)).status,404);
 assert.equal((await call('/api/trips/'+osaka.id+'/shares/'+bob.id,'PUT',{permission:'view'})).status,200);
 await login('bob');assert.deepEqual((await call('/api/trips').then(r=>r.json())).trips.map(t=>t.id),[osaka.id]);
 assert.equal((await call('/api/trips/'+osaka.id).then(r=>r.json())).permission,'view');
 assert.equal((await call('/api/trips/'+kyoto.id)).status,404);
 assert.equal((await call('/api/trips/'+osaka.id+'/shares')).status,403);
 assert.equal((await call('/api/trips/'+osaka.id,'DELETE')).status,403);
 await login('alice');assert.equal((await call('/api/trips/'+osaka.id+'/shares/'+bob.id,'PUT',{permission:'edit'})).status,200);
 await login('bob');assert.equal((await call('/api/trips/'+osaka.id).then(r=>r.json())).permission,'edit');
 assert.equal((await call('/api/trips/'+osaka.id+'/shares/'+owner.id,'PUT',{permission:'view'})).status,403);
 const current=await call('/api/trips/'+osaka.id).then(r=>r.json());current.trip.title='Bob 帮忙编辑';assert.equal((await call('/api/trips/'+osaka.id,'PUT',{revision:current.revision,trip:current.trip})).status,200);
 await login('owner');assert.deepEqual((await call('/api/trips').then(r=>r.json())).trips.map(t=>t.id),[legacyId]);
 assert.equal((await call('/api/trips/'+osaka.id)).status,404);
 assert.equal((await call('/api/users/'+alice.id,'DELETE')).status,409);
 await login('alice');assert.equal((await call('/api/trips/'+osaka.id+'/shares/'+owner.id,'PUT',{permission:'view'})).status,200);
 await login('owner');assert.deepEqual((await call('/api/trips').then(r=>r.json())).trips.map(t=>t.id),[legacyId,osaka.id]);
 assert.equal((await call('/api/trips/'+osaka.id).then(r=>r.json())).permission,'view');
 assert.equal((await call('/api/trips/'+osaka.id+'/shares')).status,403);
});
