import {mkdir,readFile,writeFile,rename} from 'node:fs/promises';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';

const fail=(message,status=400)=>Object.assign(new Error(message),{status});
const text=(value,max)=>{if(typeof value!=='string'||value.length>max)throw fail(`文字长度不能超过 ${max} 字`);return value.trim();};
const localDate=at=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(at));
export function createMemories(directory,{store,conversations}){const dir=join(directory,'memories'),file=id=>join(dir,id+'.json');let queue=Promise.resolve();
 async function source(id){const entry=await store.read(id),messages=await conversations.fullHistory(id),byStop=new Map(entry.trip.days.flatMap(day=>day.stops.map(stop=>[stop.id,day.date]))),notes=messages.filter(message=>message.role==='user').map(message=>({date:localDate(message.at),at:message.at,text:message.text,audio:!!message.audioId})),changes=messages.filter(message=>message.edits?.length).flatMap(message=>message.edits.map(edit=>({date:byStop.get(edit.stopId)||'',at:message.at,title:edit.title,fields:edit.fields})));return {trip:entry.trip,notes,changes,messageCount:messages.length};}
 function build(data){const {trip,notes,changes}=data;return {title:`${trip.cityTo||trip.title} · 旅行回忆脚本`,opening:`这趟 ${trip.days.length} 天的旅行，从 ${trip.startDate||'出发日'} 到 ${trip.endDate||'归来日'}。`,days:trip.days.map(day=>{const relevant=notes.filter(note=>note.date===day.date),stops=day.stops.map(stop=>`${stop.time||'待定时间'} ${stop.title}${stop.progress==='completed'?'（已完成）':stop.progress==='incomplete'?'（未完成）':''}`);return {date:day.date,title:day.theme||day.city,script:`${day.city} · ${day.date}\n${stops.join(' → ')}${relevant.length?'\n\n旅行时的真实感受：\n'+relevant.map(note=>'· '+note.text).join('\n'):''}`};}),closing:''};}
 async function readSaved(id){try{return JSON.parse(await readFile(file(id),'utf8'));}catch(e){if(e.code==='ENOENT')return null;throw e;}}
 async function get(id){const data=await source(id),saved=await readSaved(id),dates=new Set(data.trip.days.map(day=>day.date)),fresh=build(data),prior=new Map((saved?.draft.days||[]).map(day=>[day.date,day]));const draft=saved?{...fresh,...saved.draft,days:fresh.days.map(day=>prior.get(day.date)||day)}:fresh;return {revision:saved?.revision??0,updatedAt:saved?.updatedAt||'',saved:!!saved,draft,sources:{messageCount:data.messageCount,notes:data.notes.slice(-200),changes:data.changes.slice(-200),unassignedNotes:data.notes.filter(note=>!dates.has(note.date)).length,days:data.trip.days.map(day=>({date:day.date,city:day.city,stops:day.stops.map(stop=>({time:stop.time,title:stop.title,progress:stop.progress??'upcoming',transport:stop.transport,tips:stop.tips}))}))}};}
 async function preview(id){return {draft:build(await source(id))};}
 function save(id,revision,draft){const action=queue.then(async()=>{const trip=(await store.read(id)).trip,existing=await readSaved(id);if(revision!==(existing?.revision??0))throw fail('回忆草稿已在其他页面更新，请重新加载',409);if(!draft||typeof draft!=='object'||!Array.isArray(draft.days)||draft.days.length!==trip.days.length)throw fail('回忆草稿格式不正确');const dates=trip.days.map(day=>day.date),days=draft.days.map((day,index)=>{if(day.date!==dates[index])throw fail('回忆草稿日期与当前行程不一致');return {date:day.date,title:text(day.title,180),script:text(day.script,20000)};});const state={revision:revision+1,updatedAt:new Date().toISOString(),draft:{title:text(draft.title,180),opening:text(draft.opening,10000),days,closing:text(draft.closing,10000)}};await mkdir(dir,{recursive:true});const temp=join(dir,randomUUID()+'.tmp');await writeFile(temp,JSON.stringify(state,null,2),{mode:0o600});await rename(temp,file(id));return state;});queue=action.catch(()=>{});return action;}
 return {get,preview,save};}
