import {organizeCollections} from './collections.mjs';
export const emptyTrip=()=>({schemaVersion:1,title:'我的旅行',subtitle:'把每一天，安排成喜欢的样子。',cityFrom:'My',cityTo:'Trip',startDate:'',endDate:'',travelers:'2 人',notice:'',days:[],bookings:[],tickets:[],checklist:[],notes:[]});
export class ValidationError extends Error{}
const fail=m=>{throw new ValidationError(m);};
const obj=v=>{if(!v||typeof v!=='object'||Array.isArray(v))fail('内容格式不正确');return v;};
const str=(v,max=4000)=>{if(v===undefined)return '';if(typeof v!=='string'||v.length>max)fail(`文本必须为字符串且不超过 ${max} 字`);return v.trim();};
const required=v=>{const s=str(v,180);if(!s)fail('标题不能为空');return s;};
const date=v=>{const s=str(v,10);if(s&&(!/^\d{4}-\d{2}-\d{2}$/.test(s)||!Number.isFinite(Date.parse(s+'T12:00:00Z'))||new Date(s+'T12:00:00Z').toISOString().slice(0,10)!==s))fail('日期格式不正确');return s;};
const time=v=>{const s=str(v,5);if(s&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(s))fail('时间格式不正确');return s;};
const timestamp=v=>{const s=str(v,40);if(s&&(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(s)||!Number.isFinite(Date.parse(s))))fail('进度更新时间格式不正确');return s;};
const list=(v,max,fn)=>{if(!Array.isArray(v)||v.length>max)fail(`列表最多 ${max} 项`);return v.map(x=>fn(obj(x)));};
const choice=(v,values)=>{if(!values.includes(v))fail('选项不正确');return v;};
const url=v=>{const s=str(v,2048);if(s){try{if(!['http:','https:'].includes(new URL(s).protocol))fail('链接只支持 HTTP/HTTPS');}catch{fail('链接格式不正确');}}return s;};
const id=v=>{const s=str(v,100);if(!/^[a-zA-Z0-9_-]+$/.test(s))fail('记录编号不正确');return s;};
const attachment=v=>{if(!v)return null;obj(v);const name=str(v.name,180),asset=str(v.id,80);if(!/^[a-f0-9-]{36}\.(pdf|png|jpg)$/.test(asset)||!name)fail('附件格式不正确');return {id:asset,name};};
const photo=v=>{const asset=attachment(v);if(!asset||asset.id.endsWith('.pdf'))fail('图片参考只支持图片');return {...asset,caption:str(v.caption,300)};};
export function validateTrip(input){const t=organizeCollections(obj(input));if(t.schemaVersion!==1)fail('不支持的备份版本');
 const result={schemaVersion:1,title:required(t.title),subtitle:str(t.subtitle,300),cityFrom:str(t.cityFrom,80),cityTo:str(t.cityTo,80),startDate:date(t.startDate),endDate:date(t.endDate),travelers:str(t.travelers,80),notice:str(t.notice),
 days:list(t.days,60,d=>({id:id(d.id),date:date(d.date),city:required(d.city),cityEn:str(d.cityEn,150),theme:str(d.theme,180),intro:str(d.intro),stops:list(d.stops,200,s=>({id:id(s.id),time:time(s.time),endTime:time(s.endTime),title:required(s.title),titleEn:str(s.titleEn,200),kind:choice(s.kind,['walk','transport','flight','hotel','food','shopping','event','museum']),status:choice(s.status,['planned','confirmed','optional','done']),progress:choice(s.progress??(s.status==='done'?'completed':'upcoming'),['upcoming','active','completed','incomplete']),progressUpdatedAt:timestamp(s.progressUpdatedAt),progressUpdatedBy:choice(s.progressUpdatedBy??'', ['','manual','admin','ai']),layout:choice(s.layout??'standard',['standard','area']),shops:list(s.shops??[],40,shop=>({name:required(shop.name),detail:str(shop.detail,1000),location:str(shop.location,300),tag:str(shop.tag,30)})),description:str(s.description,10000),transport:str(s.transport),tips:str(s.tips,10000),alternative:str(s.alternative),extensions:list(s.extensions??[],30,e=>({id:id(e.id),title:required(e.title),body:str(e.body,10000)})),location:str(s.location,300),url:url(s.url),cost:str(s.cost,100),source:str(s.source,100),preparations:list(s.preparations??[],30,p=>({id:id(p.id),title:required(p.title),done:p.done===true})),photos:list(s.photos??[],20,photo)}))})),
 bookings:list(t.bookings,200,b=>({id:id(b.id),title:required(b.title),kind:choice(b.kind,['food','visit','service','other']),date:date(b.date),endDate:date(b.endDate),time:time(b.time),status:choice(b.status,['pending','confirmed','cancelled']),used:b.used===true,reference:str(b.reference,180),location:str(b.location,300),cost:str(b.cost,100),notes:str(b.notes,10000),url:url(b.url),attachment:attachment(b.attachment)})),
 tickets:list(t.tickets,200,b=>({id:id(b.id),title:required(b.title),kind:choice(b.kind,['flight','transport','hotel','admission']),date:date(b.date),endDate:date(b.endDate),time:time(b.time),status:choice(b.status,['pending','confirmed','cancelled']),reference:str(b.reference,180),location:str(b.location,300),cost:str(b.cost,100),notes:str(b.notes,10000),url:url(b.url),attachment:attachment(b.attachment)})),
 checklist:list(t.checklist,300,c=>({id:id(c.id),title:required(c.title),group:str(c.group,100),done:c.done===true,notes:str(c.notes)})),
 notes:list(t.notes,100,n=>({id:id(n.id),title:required(n.title),body:str(n.body,20000),url:url(n.url)}))};
 if(result.startDate&&result.endDate&&result.startDate>result.endDate)fail('结束日期不能早于开始日期');
 const ids=[...result.days,...result.days.flatMap(d=>d.stops),...result.days.flatMap(d=>d.stops.flatMap(s=>[...s.preparations,...s.extensions])),...result.bookings,...result.tickets,...result.checklist,...result.notes].map(x=>x.id);if(new Set(ids).size!==ids.length)fail('记录编号重复');return result;}
