import {createHash,randomUUID} from 'node:crypto';
import {mkdir,readFile,readdir,rename,stat,writeFile} from 'node:fs/promises';
import {join,relative,sep} from 'node:path';
import mysql from 'mysql2/promise';

const excluded=new Set(['backup-mysql.json','backup-status.json']);
const issue=(message,status=400)=>Object.assign(new Error(message),{status});
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');

export function createMysqlBackup(directory,{mysqlClient=mysql,intervalMs=60000}={}){
 const configPath=join(directory,'backup-mysql.json'),statusPath=join(directory,'backup-status.json');
 let running=false,timer=null,closed=false,lastFingerprint='',latest={};
 const readJson=async(path,fallback)=>{try{return JSON.parse(await readFile(path,'utf8'));}catch(e){if(e.code==='ENOENT')return fallback;throw e;}};
 const config=()=>readJson(configPath,null);
 const visible=record=>record?{host:record.host,port:record.port,database:record.database,username:record.username,ssl:record.ssl,hasPassword:!!record.password}:null;
 const connection=record=>mysqlClient.createConnection({host:record.host,port:record.port,user:record.username,password:record.password,database:record.database,ssl:record.ssl?{rejectUnauthorized:true,ca:record.ca||undefined}:undefined,connectTimeout:10000,multipleStatements:false});
 async function saveStatus(value){if(!Object.keys(latest).length)latest=await readJson(statusPath,{});latest={...latest,...value};await mkdir(directory,{recursive:true});const temp=join(directory,randomUUID()+'.tmp');await writeFile(temp,JSON.stringify(latest),{mode:0o600});await rename(temp,statusPath);}
 function validate(input,old){if(!input||typeof input!=='object'||Array.isArray(input))throw issue('数据库配置不正确');const result={host:String(input.host??old?.host??'').trim(),port:Number(input.port??old?.port??3306),database:String(input.database??old?.database??'').trim(),username:String(input.username??old?.username??'').trim(),password:input.password?String(input.password):old?.password||'',ssl:Boolean(input.ssl??old?.ssl??false),ca:String(input.ca??old?.ca??'').trim()};if(!/^[a-zA-Z0-9._-]{1,253}$/.test(result.host)||!Number.isInteger(result.port)||result.port<1||result.port>65535||!/^[a-zA-Z0-9_]{1,64}$/.test(result.database)||!/^[a-zA-Z0-9_]{1,64}$/.test(result.username)||!result.password||result.password.length>512||result.ca.length>20000)throw issue('请填写有效的主机、端口、数据库、用户名和密码');return result;}
 async function test(input){const record=validate(input,await config());let db;try{db=await connection(record);await db.query('SELECT 1');}catch(e){throw issue(`数据库连接失败（${e.code||'网络或权限错误'}）`,502);}finally{await db?.end();}return {ok:true};}
 async function configure(input){const old=await config(),record=validate(input,old);await test(record);await mkdir(directory,{recursive:true});const temp=join(directory,randomUUID()+'.tmp');await writeFile(temp,JSON.stringify(record),{mode:0o600});await rename(temp,configPath);lastFingerprint='';await saveStatus({configuredAt:new Date().toISOString(),lastError:''});start();execute({force:true}).catch(()=>{});return status();}
 async function scan(){const files=[];async function walk(dir){for(const item of await readdir(dir,{withFileTypes:true})){const path=join(dir,item.name),name=relative(directory,path).split(sep).join('/');if(excluded.has(name)||item.name.endsWith('.tmp'))continue;if(item.isDirectory())await walk(path);else if(item.isFile()){const info=await stat(path);files.push({path,name,size:info.size,mtimeMs:info.mtimeMs});}}}await walk(directory);files.sort((a,b)=>a.name.localeCompare(b.name));return files;}
 const fingerprint=files=>hash(Buffer.from(files.map(f=>`${f.name}\0${f.size}\0${f.mtimeMs}`).join('\n')));
 async function schema(db){await db.query('CREATE TABLE IF NOT EXISTS trip_backup_runs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), completed_at DATETIME(3) NULL, status VARCHAR(16) NOT NULL, file_count INT UNSIGNED NOT NULL DEFAULT 0, total_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0, source_digest CHAR(64) NOT NULL DEFAULT \'\') ENGINE=InnoDB');await db.query('CREATE TABLE IF NOT EXISTS trip_backup_objects (sha256 CHAR(64) PRIMARY KEY, byte_count BIGINT UNSIGNED NOT NULL) ENGINE=InnoDB');await db.query('CREATE TABLE IF NOT EXISTS trip_backup_chunks (sha256 CHAR(64) NOT NULL, part_number INT UNSIGNED NOT NULL, payload MEDIUMBLOB NOT NULL, PRIMARY KEY (sha256,part_number)) ENGINE=InnoDB');await db.query('CREATE TABLE IF NOT EXISTS trip_backup_entries (run_id BIGINT UNSIGNED NOT NULL, file_path VARCHAR(700) NOT NULL, sha256 CHAR(64) NOT NULL, byte_count BIGINT UNSIGNED NOT NULL, PRIMARY KEY (run_id,file_path)) ENGINE=InnoDB');}
 async function execute({force=false}={}){if(running)return {running:true};const record=await config();if(!record)throw issue('请先配置 MySQL / MariaDB 备份数据库');running=true;await saveStatus({running:true,lastAttempt:new Date().toISOString(),lastError:''});let db;try{const files=await scan(),source=fingerprint(files);if(!force&&source===lastFingerprint){await saveStatus({running:false,lastChecked:new Date().toISOString()});return {unchanged:true};}db=await connection(record);await schema(db);const [previous]=await db.query("SELECT id,source_digest FROM trip_backup_runs WHERE status='complete' ORDER BY id DESC LIMIT 1");if(!force&&previous[0]?.source_digest===source){lastFingerprint=source;await saveStatus({running:false,lastChecked:new Date().toISOString()});return {unchanged:true};}
   const payload=[];let total=0;for(const file of files){if(file.name.length>700)throw issue('备份路径过长：'+file.name);const data=await readFile(file.path),after=await stat(file.path);if(after.size!==file.size||after.mtimeMs!==file.mtimeMs)throw issue('备份时文件发生变化，请重试',409);total+=data.length;if(total>512*1024*1024)throw issue('数据已超过单次备份上限 512 MB');payload.push({name:file.name,data,sha:hash(data)});}
   await db.beginTransaction();let id;try{const [run]=await db.execute("INSERT INTO trip_backup_runs(status,file_count,total_bytes,source_digest) VALUES ('running',?,?,?)",[payload.length,total,source]);id=run.insertId;for(const file of payload){const [result]=await db.execute('INSERT IGNORE INTO trip_backup_objects(sha256,byte_count) VALUES (?,?)',[file.sha,file.data.length]);if(result.affectedRows){for(let offset=0,part=0;offset<file.data.length;offset+=2*1024*1024,part++)await db.execute('INSERT INTO trip_backup_chunks(sha256,part_number,payload) VALUES (?,?,?)',[file.sha,part,file.data.subarray(offset,offset+2*1024*1024)]);}await db.execute('INSERT INTO trip_backup_entries(run_id,file_path,sha256,byte_count) VALUES (?,?,?,?)',[id,file.name,file.sha,file.data.length]);}await db.execute("UPDATE trip_backup_runs SET status='complete',completed_at=NOW(3) WHERE id=?",[id]);await db.commit();}catch(e){await db.rollback();throw e;}
   lastFingerprint=source;const success={id:Number(id),files:payload.length,bytes:total,at:new Date().toISOString()};await saveStatus({running:false,lastSuccess:success,lastError:'',lastChecked:success.at});return success;
  }catch(e){const label=e.status?e.message:`备份失败（${e.code||'数据库或磁盘错误'}）`;await saveStatus({running:false,lastError:label,lastFailedAt:new Date().toISOString()});throw e;}finally{running=false;await db?.end();}}
 let initialTimer=null;
 function start(){if(timer||closed)return;timer=setInterval(()=>{execute().catch(()=>{});},intervalMs);timer.unref?.();initialTimer=setTimeout(()=>{if(!closed)execute().catch(()=>{});},2000);initialTimer.unref?.();}
 async function status(){if(!Object.keys(latest).length)latest=await readJson(statusPath,{});const record=await config();return {configured:!!record,settings:visible(record),running,lastSuccess:latest.lastSuccess||null,lastError:latest.lastError||'',lastAttempt:latest.lastAttempt||'',lastChecked:latest.lastChecked||''};}
 async function trigger(){const record=await config();if(!record)throw issue('请先配置 MySQL / MariaDB 备份数据库');if(running)return {running:true};execute({force:true}).catch(()=>{});return {running:true};}
 function close(){closed=true;if(timer)clearInterval(timer);if(initialTimer)clearTimeout(initialTimer);}
 config().then(record=>{if(record)start();}).catch(()=>{});
 return {status,test,configure,trigger,execute,close};
}
